### ISSUE TITLE
Licensing information?

### ISSUE THREAD

**Issue by ColinGilbert** [jaecktec/aws-cdk-appmesh-example#1]
Hi,

Unlicensed code is unusable code. Could we please have a license for this, for peace of mind?

**Comment by jaecktec** [comment]
ah sure - since it was just ment as an easy way to query the code for the dev.to article I didn't think about a license. 
is MIT ok?

**Comment by ColinGilbert** [comment]
That would be perfect. Thank you so much!

**Comment by jaecktec** [comment]
Happy that my work helps someone :) maybe also leave a like on the dev.to article, that would make me happy (Numbers go up make monkey brain happy)

**Comment by ColinGilbert** [comment]
Definitely will!
